Traceback (most recent call last):
  File "/home/runner/work/lessons/lessons/.nox/docs/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/work/lessons/lessons/.nox/docs/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/lessons/lessons/.nox/docs/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/work/lessons/lessons/.nox/docs/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/work/lessons/lessons/.nox/docs/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/work/lessons/lessons/.nox/docs/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# This is the preferred way to catch an error 
def clean_title(title):
    """
    Attempts to return the first character of the title.

    Raises the same error with a friendly message if the input is invalid.
    """
    try:
        return title[0]
    except IndexError as e:
        raise IndexError(f"Oops! You provided a title in an unexpected format. I expected the title to be provided in a list and you provided a {type(title)}.") 

# Example usage:
title = ""
print(clean_title(title))  # This will raise an IndexError with the friendly message
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mIndexError[0m                                Traceback (most recent call last)
Cell [0;32mIn[3], line 9[0m, in [0;36mclean_title[0;34m(title)[0m
[1;32m      8[0m [38;5;28;01mtry[39;00m:
[0;32m----> 9[0m     [38;5;28;01mreturn[39;00m [43mtitle[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m
[1;32m     10[0m [38;5;28;01mexcept[39;00m [38;5;167;01mIndexError[39;00m [38;5;28;01mas[39;00m e:

[0;31mIndexError[0m: string index out of range

During handling of the above exception, another exception occurred:

[0;31mIndexError[0m                                Traceback (most recent call last)
Cell [0;32mIn[3], line 15[0m
[1;32m     13[0m [38;5;66;03m# Example usage:[39;00m
[1;32m     14[0m title [38;5;241m=[39m [38;5;124m"[39m[38;5;124m"[39m
[0;32m---> 15[0m [38;5;28mprint[39m([43mclean_title[49m[43m([49m[43mtitle[49m[43m)[49m)  [38;5;66;03m# This will raise an IndexError with the friendly message[39;00m

Cell [0;32mIn[3], line 11[0m, in [0;36mclean_title[0;34m(title)[0m
[1;32m      9[0m     [38;5;28;01mreturn[39;00m title[[38;5;241m0[39m]
[1;32m     10[0m [38;5;28;01mexcept[39;00m [38;5;167;01mIndexError[39;00m [38;5;28;01mas[39;00m e:
[0;32m---> 11[0m     [38;5;28;01mraise[39;00m [38;5;167;01mIndexError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mOops! You provided a title in an unexpected format. I expected the title to be provided in a list and you provided a [39m[38;5;132;01m{[39;00m[38;5;28mtype[39m(title)[38;5;132;01m}[39;00m[38;5;124m.[39m[38;5;124m"[39m)

[0;31mIndexError[0m: Oops! You provided a title in an unexpected format. I expected the title to be provided in a list and you provided a <class 'str'>.

